# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/DetectErrorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(425, 434)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 381, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.limit = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.limit.setObjectName("limit")
        self.horizontalLayout_7.addWidget(self.limit)
        self.limitValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.limitValue.setEnabled(True)
        self.limitValue.setText("")
        self.limitValue.setObjectName("limitValue")
        self.horizontalLayout_7.addWidget(self.limitValue)
        self.limitSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.limitSlider.setOrientation(QtCore.Qt.Horizontal)
        self.limitSlider.setObjectName("limitSlider")
        self.horizontalLayout_7.addWidget(self.limitSlider)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.statusButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.statusButton.setObjectName("statusButton")
        self.horizontalLayout_8.addWidget(self.statusButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.elapsed = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.elapsed.setObjectName("elapsed")
        self.horizontalLayout_3.addWidget(self.elapsed)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.detectionTimes = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.detectionTimes.setObjectName("detectionTimes")
        self.horizontalLayout_2.addWidget(self.detectionTimes)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.generateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout_4.addWidget(self.generateButton)
        self.fileList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.fileList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileList.sizePolicy().hasHeightForWidth())
        self.fileList.setSizePolicy(sizePolicy)
        self.fileList.setObjectName("fileList")
        self.verticalLayout_4.addWidget(self.fileList)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.limit.setText(_translate("Form", "limit"))
        self.pushButton.setText(_translate("Form", "set"))
        self.statusButton.setText(_translate("Form", "start"))
        self.label.setText(_translate("Form", "Time:"))
        self.elapsed.setText(_translate("Form", "0:00:00"))
        self.label_5.setText(_translate("Form", "Detected"))
        self.detectionTimes.setText(_translate("Form", "0"))
        self.generateButton.setText(_translate("Form", "Generate Image "))

